### ISSUE TITLE
Getting error while deployment

### ISSUE THREAD

**Issue by chintan1891** [bettiolo/7digital-gracenote-radio#1]
Hi,
I am trying to deploy this solution, but i am getting below error.

> DEBUG=app nodemon --ignore public/ --ignore views/ ./bin/www

29 Jan 13:37:33 - [nodemon] v1.3.5
29 Jan 13:37:33 - [nodemon] to restart at any time, enter `rs`
29 Jan 13:37:33 - [nodemon] watching: _._
29 Jan 13:37:33 - [nodemon] starting `node ./bin/www`

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at EventEmitter.app.listen (/Users/chintanprajapati/Downloads/7digital-gracenote-radio-master/node_modules/express/lib/application.js:559:24)
    at Object.<anonymous> (/Users/chintanprajapati/Downloads/7digital-gracenote-radio-master/bin/www:8:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
29 Jan 13:37:33 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by bettiolo** [comment]
Hi,
You are getting that error because the app is trying to bind to port 3000 and that port is not free on your machine. 
This is where it is binding to the port: https://github.com/bettiolo/7digital-gracenote-radio/blob/master/bin/www#L8 and it is getting the port number from https://github.com/bettiolo/7digital-gracenote-radio/blob/master/config.js#L10

**Comment by chintan1891** [comment]
@bettiolo thanks.. its working now..
